version: '2'

services:
  bureaudechange:
    build: src/bureaudechange
    volumes:
      - ./src/bureaudechange:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8000
    links:
      - api

  api:
    build: src/api
    volumes:
      - ./src/api/euskoapi:/usr/src/app
    ports:
      - 8000:8000
    links:
      - dolibarr-app
      - cyclos-app

  dolibarr-app:
    image: euskalmoneta/dolibarr:develop
    ports:
      - 8080:80
    volumes:
      - ./data/documents:/var/www/documents
      - ./etc/dolibarr/conf.php:/var/www/html/conf/conf.php
    links:
      - dolibarr-db
      - cyclos-app

  dolibarr-db:
    image: mariadb:10.1
    volumes:
      - ./etc/dolibarr/dump:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=pass
      - MYSQL_USER=pass
      - MYSQL_PASSWORD=pass

  cyclos-app:
    image: cyclos/cyclos
    ports:
      - 8081:8080
    environment:
      - DB_HOST=cyclos-db
      - DB_NAME=cyclos
      - DB_USER=cyclos
      - DB_PASSWORD=cyclos
    links:
      - cyclos-db

  cyclos-db:
    image: cyclos/db
    volumes:
      - ./etc/cyclos/dump/cyclos.sql:/docker-entrypoint-initdb.d/cyclos.sql
      - ./data/cyclos/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cyclos
      - POSTGRES_USER=cyclos
      - POSTGRES_PASSWORD=cyclos

  sentry-redis:
    image: redis

  sentry-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sentry
      - POSTGRES_USER=sentry
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  sentry:
    image: sentry
    environment:
      - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
      - SENTRY_POSTGRES_HOST=sentry-postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
      - SENTRY_REDIS_HOST=sentry-redis
    ports:
      - 9000:9000
    links:
      - sentry-redis:redis
      - sentry-postgres:postgres

  sentry-cron:
    image: sentry
    environment:
      - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
      - SENTRY_POSTGRES_HOST=sentry-postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
      - SENTRY_REDIS_HOST=sentry-redis
    links:
      - sentry-redis:redis
      - sentry-postgres:postgres
    command: sentry run cron

  sentry-worker:
    image: sentry
    environment:
      - SENTRY_SECRET_KEY="x4^nd^1k9k8=8#sa1$gu72p-g15a(ft8(d@jy@^d$ec!oe!"
      - SENTRY_POSTGRES_HOST=sentry-postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
      - SENTRY_REDIS_HOST=sentry-redis
    links:
      - sentry-redis:redis
      - sentry-postgres:postgres
    command: sentry run worker
