version: '2'
services:
  cyclos-db:
    image: cyclos/db
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=examplepwd
  cyclos-app:
    depends_on:
      - cyclos-db
    image: cyclos/cyclos
    ports:
      - 8080:8080
    environment:
      - DB_HOST=cyclos-db
      - DB_NAME=example
      - DB_USER=example
      - DB_PASSWORD=examplepwd
